Update onboarding design
CirclesUBI/circles-myxogastria pull request #267
Opened 2021-12-07 12:33 UTC by mikozet

2021-12-13 14:12 UTC, adzialocha commented on src/hooks/header.js
> +import { useScrollTrigger } from '@material-ui/core';
Maybe this file could be named `scrollTrigger.js` or similar?

2021-12-13 14:12 UTC, adzialocha commented on src/styles/theme.js
> +    // box-shadow 300ms cubic-bezier(0.4, 0, 0.2, 1) 0ms;
Looks like something made its way here :-D

2021-12-13 14:13 UTC, adzialocha commented on src/components/Tutorial.js
> +    background: `${theme.palette.common.white}`,
No backticks are needed here.

2021-12-13 14:13 UTC, adzialocha commented on src/components/Tutorial.js
> +    transition: `${theme.transitions.create(['background'], {
Same here?

2021-12-13 14:14 UTC, adzialocha commented on src/components/Tutorial.js
> +    backgroundColor: `${theme.palette.common.white}`,
No backticks needed here :+1:

2021-12-13 14:15 UTC, adzialocha commented on src/components/BackgroundCurved.js
> +    background: 'linear-gradient(180deg, #48B2B7 0%, #06FC9D 100%)',
Could be cool to get the colors from somewhere where they have been defined, probably here: https://github.com/CirclesUBI/circles-myxogastria/blob/main/src/styles/theme.js#L30

2021-12-13 14:15 UTC, adzialocha reviewed
Yay! This looks really good! :sparkles:  I've just added some smaller notes here, but only details.

2021-12-13 14:17 UTC, adzialocha commented on src/components/BackgroundCurved.js
> +    background: 'linear-gradient(180deg, #48B2B7 0%, #06FC9D 100%)',
Similar actually with the `zIndex`, its nice when they are all defined in one place.

2021-12-16 14:42 UTC, louilinn commented
Just to be clear, we will not merge any visual updates into preview until current updates from Milestone "Summer updates" are merged into main.

2021-12-23 12:21 UTC, louilinn requested changes
Nicely done fixing @adzialocha comments @mikozet :star: 
I think the code looks good.

However looking at the UI I think we have some work left. I will make a comment with some screen shots. Basically the radius of the circles seems like it should be constant.

2021-12-23 12:24 UTC, louilinn commented
I am not sure how to fix this exactly.. but some screenshots for reference:
Also I think the color is a bit too light? Or the fading starts too early in the top?

![Screenshot from 2021-12-23 13-17-14](https://user-images.githubusercontent.com/20553836/147240071-7455e650-ca2c-4fc5-bcb8-ef6b1d219193.png)
![Screenshot from 2021-12-23 13-17-37](https://user-images.githubusercontent.com/20553836/147240078-a175bae3-5592-41d8-87ce-f00113c1d3a0.png)
![Screenshot from 2021-12-23 13-17-56](https://user-images.githubusercontent.com/20553836/147240081-c0362f43-a719-4b60-a008-24582bb2aa77.png)
![Screenshot from 2021-12-23 13-21-40](https://user-images.githubusercontent.com/20553836/147240083-cab1b1c1-9b73-4917-845c-b4b675119983.png)

2022-01-07 12:59 UTC, mikozet commented
> I am not sure how to fix this exactly.. but some screenshots for reference: Also I think the color is a bit too light? Or the fading starts too early in the top?
> 

@I correct it
![Zrzut ekranu 2022-01-7 o 13 55 42](https://user-images.githubusercontent.com/95082155/148547343-8833c082-f9e7-499f-a22d-61616c564f55.png)

2022-01-25 08:52 UTC, mikozet commented
Update with commit which solves as well large desktop screens

2022-06-09 12:46 UTC, louilinn commented
@mikozet this is an outdated PR right? If not you can reopen

2022-06-09 12:46 UTC, closed without merging