New validation process
CirclesUBI/circles-myxogastria pull request #330
Opened 2022-04-25 07:27 UTC by mikozet

2022-05-03 14:09 UTC, louilinn reviewed
These are my comments so far. I will also post some screenshots!

2022-05-03 14:09 UTC, louilinn commented on src/components/OnboardingStepper.js
> +          <CopyToClipboardBtn onClick={onFinish} />
What is the intention here?

2022-05-03 14:09 UTC, louilinn commented on src/views/Validation.js
> +              disabled={isReady ? false : true}
you could simply write `!isReady`

2022-05-03 14:09 UTC, louilinn commented on src/views/Validation.js
>    const isDeploymentReady =
what is the difference between isDeploymentReady and isReady? Can we make names clearer, in the comment below "Attempt deployment if one of two conditions is met" makes them sound the same based on naming

2022-05-03 14:09 UTC, louilinn commented on locales/en.json
>      "buttonShareProfileLink": "Share Profile Link",
Not related to the implementation work but I think we should have a different text in place of "Create account" button which appears after you get a notification your account is created @triaslucia

2022-05-03 14:09 UTC, louilinn commented on src/components/ValidationStatus.js
> +    return null;
is this what we want?

2022-05-03 14:10 UTC, louilinn commented on locales/en.json
>      "buttonShareProfileLink": "Share Profile Link",
eg "Start using Circles" or "Finalize account" etc

2022-05-03 14:14 UTC, louilinn commented
This is different than the design

![Screenshot from 2022-05-03 16-00-39](https://user-images.githubusercontent.com/20553836/166470086-6a01ff6f-950d-4940-8656-1f2abfd5f3cf.png)
![Screenshot from 2022-05-03 16-01-36](https://user-images.githubusercontent.com/20553836/166470094-3cd87ec7-5666-4177-be62-0acfe73ff6f5.png)
![Screenshot from 2022-05-03 16-02-40](https://user-images.githubusercontent.com/20553836/166470097-d074ae5a-6f77-4a40-9cc3-80845a9957d1.png)
![Screenshot from 2022-05-03 16-13-26](https://user-images.githubusercontent.com/20553836/166470101-83b70588-46a4-4a9c-9b78-5ac104a37860.png)

2022-05-03 14:17 UTC, louilinn commented
The padding of dialogues seems inconsistent

![Screenshot from 2022-05-03 16-11-58](https://user-images.githubusercontent.com/20553836/166470460-cbd81ce6-c9b9-47ec-83c9-2a19441afe35.png)
![Screenshot from 2022-05-03 16-04-59](https://user-images.githubusercontent.com/20553836/166470465-e63cf35b-d04c-40a7-a9e1-4015a2ce598d.png)

2022-05-03 14:19 UTC, louilinn commented
There is an issue with buttons when closing dialogues or going back, highlighting gets stuck somehow

![Screenshot from 2022-05-03 15-38-36](https://user-images.githubusercontent.com/20553836/166470846-2efd280b-09ef-4a3c-bec2-5c9c13ee3a76.png)
![Screenshot from 2022-05-03 15-48-38](https://user-images.githubusercontent.com/20553836/166470923-8d13781f-7bad-4fbb-a8e1-08120205164f.png)

2022-05-03 14:20 UTC, louilinn requested changes
Requested changes based on screenshots

2022-05-06 12:57 UTC, mikozet commented on src/components/OnboardingStepper.js
> +          <CopyToClipboardBtn onClick={onFinish} />
So stepsButtons is a configuration object where we decide which buttons should be displayed. So once there is an attribute `additionalBtnSecond` we tell which component should be displayed in this particular place. Here we check for that attribute and display component

2022-05-10 13:53 UTC, mikozet commented on src/views/Validation.js
> +              disabled={isReady ? false : true}
corrected

2022-05-10 13:58 UTC, mikozet commented on src/views/Validation.js
>    const isDeploymentReady =
I removed `isReady` - it was remainings from old code which I believe we don't need

2022-05-10 14:08 UTC, mikozet commented on locales/en.json
>      "buttonShareProfileLink": "Share Profile Link",
Good point, let's talk about it with Lucia on UX meeting

2022-05-10 14:09 UTC, mikozet commented on src/components/ValidationStatus.js
> +    return null;
I removed it as I believe it is redundant - it is from old codebase..

2022-05-10 14:10 UTC, mikozet commented
> The padding of dialogues seems inconsistent
> 
> ![Screenshot from 2022-05-03 16-11-58](https://user-images.githubusercontent.com/20553836/166470460-cbd81ce6-c9b9-47ec-83c9-2a19441afe35.png) ![Screenshot from 2022-05-03 16-04-59](https://user-images.githubusercontent.com/20553836/166470465-e63cf35b-d04c-40a7-a9e1-4015a2ce598d.png)

I corrected it

2022-05-10 14:10 UTC, mikozet commented
> There is an issue with buttons when closing dialogues or going back, highlighting gets stuck somehow
> 
> ![Screenshot from 2022-05-03 15-38-36](https://user-images.githubusercontent.com/20553836/166470846-2efd280b-09ef-4a3c-bec2-5c9c13ee3a76.png) ![Screenshot from 2022-05-03 15-48-38](https://user-images.githubusercontent.com/20553836/166470923-8d13781f-7bad-4fbb-a8e1-08120205164f.png)

I am not able to replicate it - could you describe what do you do?

2022-05-13 08:55 UTC, louilinn commented
> 

I open a dialog then close it and then it happens, or going back a step. I will try again

2022-05-13 08:57 UTC, louilinn commented on src/components/ValidationStatus.js
> -  }
why was it redundant?

2022-05-13 09:03 UTC, louilinn commented
> This is different than the design
> 
> ![Screenshot from 2022-05-03 16-00-39](https://user-images.githubusercontent.com/20553836/166470086-6a01ff6f-950d-4940-8656-1f2abfd5f3cf.png) ![Screenshot from 2022-05-03 16-01-36](https://user-images.githubusercontent.com/20553836/166470094-3cd87ec7-5666-4177-be62-0acfe73ff6f5.png) ![Screenshot from 2022-05-03 16-02-40](https://user-images.githubusercontent.com/20553836/166470097-d074ae5a-6f77-4a40-9cc3-80845a9957d1.png) ![Screenshot from 2022-05-03 16-13-26](https://user-images.githubusercontent.com/20553836/166470101-83b70588-46a4-4a9c-9b78-5ac104a37860.png)

So what about this?

2022-05-13 09:49 UTC, mikozet commented
> 

I have created additional task Regarding Re-design of the Validation process as there is a missing feature
https://github.com/CirclesUBI/circles-myxogastria/issues/325

2022-05-13 13:12 UTC, louilinn approved these changes
Complementing changes in this PR https://github.com/CirclesUBI/circles-myxogastria/issues/325
All good, lets review the entirety with Lucia later in preview. 
Great work! :star:

2022-05-13 13:14 UTC, merged