464 refactoring input components new3
CirclesUBI/circles-myxogastria pull request #508
Opened 2022-10-12 12:50 UTC by mikozet

2022-10-14 13:11 UTC, louilinn commented
I do not see this state, it seems only hoover and active state is used in the app for error message version?
![Uploading Screenshot from 2022-10-14 15-09-15.png…]()

2022-10-14 13:23 UTC, louilinn requested changes
Great job! Works as intended :) except one comment I already made in this PR. Some small DRY code comments only

2022-10-14 13:23 UTC, louilinn commented on src/components/Input.js
> +      isOrganization
these things are repeated a lot. Please define constants for color based on organization and DRY :)

2022-10-14 13:23 UTC, louilinn commented on src/components/Input.js
> +          ? theme.custom.colors.cornflowerBlue
Also repeated code

2022-10-20 10:07 UTC, mikozet commented
>I do not see this state, it seems only hoover and active state is used in the app for error message version?
Uploading Screenshot from 2022-10-14 15-09-15.png…

The link is broken for me but I think I know what do you mean and I apply change - default state for error Input

2022-10-24 09:11 UTC, mikozet commented
Hi @louilinn It seems like I didn't push changes before but now they are there ready to review :)

2022-10-27 10:56 UTC, mikozet commented
> Hi @louilinn It seems like I didn't push changes before but now they are there ready to review :)
> 
> Sorry I still don't see those changes - I am checking now what have happened

Forgot to write - all is good now :)

2022-11-17 10:51 UTC, louilinn commented
@mikozet in the latest version on figma, also the search field has this design, so all input fields should have this design
so 
- [ ] replace search input field
- [ ] remove any legacy code connected to the old input field

2022-11-17 11:12 UTC, louilinn commented
Also I think something happened.. The hover state in the design is now the active state and the active state is never used.
Current behaviour
writing in field ("active") - has hover design (incorrect)
hovering on field - has hover design (correct)
leaving the field to click on other things and not hovering - has default state (correct)

This is the same for all thre colors/themes

2022-11-23 10:43 UTC, louilinn commented
I think we can leave the search field update for now but please fix this asap so we can demo:

> Also I think something happened.. The hover state in the design is now the active state and the active state is never used. Current behaviour writing in field ("active") - has hover design (incorrect) hovering on field - has hover design (correct) leaving the field to click on other things and not hovering - has default state (correct)
> 
> This is the case for purple (shared wallet) and pink (error) but not blue (private wallet)

2022-12-06 10:46 UTC, mikozet commented
Hi @louilinn it is ready again to review. Bear in mind that input can be active + hovered or just active.

2022-12-15 14:29 UTC, louilinn reviewed
So I'm not sure but feels like if you enter the finder view from shared wallet it should have shared wallet theme?
Or do we always use blue for search?

2022-12-16 09:29 UTC, mikozet commented
> So I'm not sure but feels like if you enter the finder view from shared wallet it should have shared wallet theme? Or do we always use blue for search?

You are right it is corrected now

2022-12-16 14:06 UTC, merged