494 display do not refresh msg
CirclesUBI/circles-myxogastria pull request #527
Opened 2022-10-28 14:10 UTC by mikozet

2022-11-11 16:39 UTC, louilinn commented
There is no issue linked to this PR or any context provided

2022-11-14 09:00 UTC, louilinn commented
Closes https://github.com/CirclesUBI/circles-myxogastria/issues/494

2022-12-06 16:48 UTC, louilinn requested changes
Looks good in general!
Missing an explanation on how to use COLOR variable in .env
And customization of the general notification USER_NOTIFICATION
Not sure if necessary.

If you have too much I can do the fixes, as long as you explain what should be possible in color. Is it only hex strings? Or can we do gradient or theme colors etc?

2022-12-06 16:48 UTC, louilinn commented on .env.example
>  USER_NOTIFICATION=
No customization for the universal user notification?

2022-12-06 16:48 UTC, louilinn commented on .env.example
> +USER_NOTIFICATION_DASHBOARD_COLOR=
Can we specify the functionality of these variables?

```
# Icons can be any icon that is defined in iconSelector in icons.js
# Undefined icon defaults to iconAlert (a bell)
# Colors can be any a hex such as "#A83297" or ???? 
# Color defaults to fountain blue (#48B2B7)
``

2022-12-06 16:48 UTC, louilinn commented on src/components/AppNote.js
> +    text: process.env.USER_NOTIFICATION,
I would change to 
```
 default: {
    color: process.env.USER_NOTIFICATION_COLOR || theme.custom.colors.fountainBlue,
    icon: process.env.USER_NOTIFICATION_ICON || 'IconAlert',
    text: process.env.USER_NOTIFICATION,
  },
  ```
  After adding those variables

2022-12-08 08:28 UTC, mikozet commented
I resolve comments and update internal documentation file

2023-01-23 09:01 UTC, mikozet commented
@louilinn for some reason this branch doesn't build for me correctly on development.

I created another PR: https://github.com/CirclesUBI/circles-myxogastria/pull/582/commits

2023-01-23 09:01 UTC, closed without merging