Update handling errors
CirclesUBI/circles-myxogastria pull request #557
Opened 2022-12-09 06:32 UTC by mikozet

2022-12-15 14:01 UTC, louilinn requested changes

2022-12-15 14:01 UTC, louilinn commented on src/views/EditProfile.js
> +        const userEmail = await core.user.getEmail(safe.currentAccount);
Why not only 

`
const userEmail = await core.user.getEmail(safe.currentAccount) || '';`

I don't think we should log this as an error?

2022-12-16 08:11 UTC, mikozet commented on src/views/EditProfile.js
> +        const userEmail = await core.user.getEmail(safe.currentAccount);
I think catch is more secure here as the line which you have mentioned will not register if it is an error object I believe. 
Generally we should log all type of errors as a good practice as it is easier to debug in future

2022-12-16 14:39 UTC, louilinn commented on src/views/EditProfile.js
> +        const userEmail = await core.user.getEmail(safe.currentAccount);
Yes I agree we should log errors but I think for fetching user data that doesnt exist we shouldnt log it as an error. For example when an account doesnt have a usename we don't log it as an error - then the address is displayed instead. Why should a missing email be an error? 
You can see in username.js how we deal with no avatar or no username.
I think we want to make it possible to remove email at some point and also for data erasure requests. These accounts shouldn't then have an email and it is then incorrect to log an error. 
If there is an error with the core call (unlike returning null which isn't an error) there will still be an error? Then we should have try catch around everything in the app which isnt what this issue requests

2022-12-21 18:33 UTC, louilinn reviewed
Would you like to elaborate on why you didn't like the suggestion I proposed?

`const userEmail = await core.user.getEmail(safe.currentAccount) || '';`

2022-12-21 18:33 UTC, louilinn commented on src/views/EditProfile.js
> +        if (userEmail.status !== 404) {
I don't see getEmail ever returning an object with a status attribute?
https://github.com/CirclesUBI/circles-core/blob/e838131b64ae82be2b30fa12e4cb6f2a042f53f0/src/user.js#L270

2022-12-22 03:16 UTC, mikozet commented
> 



> Would you like to elaborate on why you didn't like the suggestion I proposed?
> 
> `const userEmail = await core.user.getEmail(safe.currentAccount) || '';`

I just doesn't feel like it would solve the issue here. If you get 404 from that query how would it save it from crashing?

2022-12-22 18:45 UTC, llunaCreixent submitted a review, later dismissed
Tested with dockers and correctly reproduced the error with the main branch, and it's solved woth this branch.
I created an account and removed the user entry in the docker db to reproduce the user case.

Good work!

2022-12-23 13:25 UTC, louilinn commented
I don't feel that I can comment further on code quality as I cannot test it (without having such an account). So since lluna is the one to test I leave it to her to also review the code quality and if all these if else statements are necessary. And in that case approve the PR @llunaCreixent

2022-12-23 13:59 UTC, llunaCreixent commented
> I don't feel that I can comment further on code quality as I cannot test it (without having such an account). So since lluna is the one to test I leave it to her to also review the code quality and if all these if else statements are necessary. And in that case approve the PR @llunaCreixent 

@louilinn you can test locally by removing the entry in the docker database after creating the account.

2023-01-03 12:44 UTC, llunaCreixent commented
The solution that @louilinn suggested works better because it doesn't produce an "Uncaught Promise" error.
When the api is down, we get `400` error, When not found we receive `404`. But in any case we display empty email.

2023-01-03 12:44 UTC, llunaCreixent approved these changes, later dismissed

2023-01-04 10:02 UTC, mikozet commented
> The solution that @louilinn suggested works better because it doesn't produce an "Uncaught Promise" error.
> When the api is down, we get `400` error, When not found we receive `404`. But in any case we display empty email.

When we get 404 it is an object so how we will get an empty email? It is a valid response I believe

2023-01-05 15:22 UTC, louilinn approved these changes

2023-01-05 15:23 UTC, merged