Add loading dialog after sending Circles
CirclesUBI/circles-myxogastria pull request #601
Opened 2023-02-10 08:07 UTC by mikozet

2023-02-10 15:50 UTC, louilinn commented
Sorry to say you prove the confirm transfer dialogue. Fix that and I'll check the code :)

## Dialogue state here
![Screenshot from 2023-02-10 16-46-52](https://user-images.githubusercontent.com/20553836/218134545-a0408e69-fe7f-41e5-8b02-57ac85fd9330.png)

## Dialogue state on main
![Screenshot from 2023-02-10 16-43-32](https://user-images.githubusercontent.com/20553836/218133803-d285161d-ecbd-42d3-ac08-c13780289878.png)

## Waiting - looks fine
![Screenshot from 2023-02-10 16-43-39](https://user-images.githubusercontent.com/20553836/218133801-5b392d20-aa6c-4132-b643-6b545abf22d2.png)

2023-02-10 15:52 UTC, louilinn commented on src/views/SendConfirm.js
> +      <SendConfirmDialog
needs username

2023-02-10 15:54 UTC, louilinn commented on src/components/SendConfirmDialog.js
> +  receiver: PropTypes.string,
required

2023-02-10 15:54 UTC, louilinn commented on src/views/SendConfirm.js
> +        sender={sender}
and receiver

2023-02-10 15:55 UTC, louilinn requested changes
See comments

2023-02-26 21:55 UTC, louilinn commented
I fixed the issues mentioned in my review
- [x] receiver username displaying
- [x] cancel button behavior fixed
- [x] clicking outside the dialog while loading does not close dialog
- [x] replaced too techy read more url with generic FAQ url
- [x] rebased (fixed button styling)

What remains
- [ ] get a better url and add it using constants.js

2023-02-26 22:09 UTC, louilinn commented
@mikozet pls chack my changes :)

2023-02-27 06:38 UTC, mikozet commented
@louilinn loos good to me :) - I am an author so I cannot approve

2023-02-28 09:33 UTC, louilinn approved these changes

2023-02-28 14:48 UTC, merged