Add export statement for personal wallet
CirclesUBI/circles-myxogastria pull request #737
Opened 2023-09-22 09:26 UTC by mikozet

Currently build on:
https://preview-dev.circles.garden/activities

2023-09-25 07:19 UTC, juanenrisley submitted a review, later dismissed
👍🏿

2023-09-25 13:49 UTC, louilinn requested changes
We need to add a description for UBI payouts. I suggest writing `CirclesUBI` in column ` To_or_from_username` and `UBI payout` in `Payment_note` for those transactions. under condition safeAddress === ZERO_ADDRESS

![Screenshot from 2023-09-25 15-44-48](https://github.com/CirclesUBI/circles-myxogastria/assets/20553836/15a859d1-1e2b-4b1b-8484-cef15da5c957)

2023-09-25 14:05 UTC, louilinn approved these changes, later dismissed
Fixed :)
Merge pending for Lucia's acceptance

2023-09-25 14:09 UTC, louilinn commented
![Uploading Screenshot from 2023-09-25 16-09-10.png…]()

2023-09-26 14:33 UTC, louilinn commented on src/utils/fileExports.js
> +      data.paymentNote = translate('ExportStatement.exportPaymentNote');
now we are adding some text in translations but not all. Maybe then I should add all fields in en.json

2023-09-26 14:33 UTC, louilinn commented on src/utils/fileExports.js
> +    throw new Error(translate('ExportStatement.exportDataName'));
this was the wrong text so I changed it in a commit

2023-09-27 14:32 UTC, juanenrisley approved these changes
👍🏿

2023-09-28 12:18 UTC, merged